Repository = memory

Clients_text = data/clients.txt
Sessions_text = data/sessions.txt

Clients_binary = data/clients.bin
Sessions_binary = data/sessions.bin

Clients_json = data/clients.json
Sessions_json = data/sessions.json

Clients_xml = data/clients.xml
Sessions_xml = data/sessions.xml

Location_db = data/gym.db